### ISSUE TITLE
Query instance contains an unwanted property with confusing name.

### ISSUE THREAD

**Issue by Papooch** [nestjs-architects/typed-cqrs#4]
**Describe the bug**

**To Reproduce**

1. Create a new Query from `@nestjs-architects/typed-cqrs` 
2. Use it in QueryHandler
3. Observe that a rogue property exists on the instance

**Expected behavior**
Ony properties that I defined should be visible

**Screenshots**
![image](https://github.com/nestjs-architects/typed-cqrs/assets/46406259/8346842a-5652-44d4-b666-bda3e392bb2b)

**Additional context**
This is likely due to the fact that typescript didn't support symbol keys in previous versions. Now, this property can be hidden using this technique. (or perhaps it can be made `protected` or `private` at least)

**Comment by Papooch** [comment]
@Sikora00 Hey, sorry for the ping. Would you consider looking at the PR?

I have been adding this library on every NestJS project where `@nestjs/cqrs` was used, because the value added is immense.

However, it always bugged me that there was the rouge type branding property, so I sometimes ended up just copying the library over, since it's just a couple of lines of code, but I'd rather not have to do it.

 I understand you may have better things to do now, so if you wouldn't mind, I'm offering to become a maintainer of this repository.
I know I could just fork it and publish it under my alias, but that doesn't feel right to me.

**Comment by Sikora00** [comment]
What are you saying, man? Let's do it
